const DAYS=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
const RECIPES=[
 {id:"oats",name:"Yogurt overnight oats",type:"breakfast",diet:["balanced","vegetarian","high-protein"],kcal:430,ingredients:{"Oats":"80 g","Greek yogurt":"1 tub","Bananas":"1","Milk":"150 ml"}},
 {id:"eggs",name:"Eggs, toast and tomato",type:"breakfast",diet:["balanced","vegetarian","high-protein"],kcal:470,ingredients:{"Eggs":"2","Wholegrain bread":"2 slices","Tomatoes":"1","Olive oil":"1 tsp"}},
 {id:"chickenRice",name:"Paprika chicken rice bowl",type:"main",diet:["balanced","high-protein"],kcal:690,ingredients:{"Chicken breast":"180 g","Basmati rice":"90 g","Frozen mixed vegetables":"200 g","Paprika":"1 tsp","Olive oil":"1 tbsp"}},
 {id:"lentil",name:"Spanish-style lentil stew",type:"main",diet:["balanced","vegetarian"],kcal:610,ingredients:{"Red lentils":"100 g","Tomatoes":"2","Carrots":"1","Onions":"1","Potatoes":"200 g","Olive oil":"1 tbsp"}},
 {id:"pasta",name:"Tomato tuna pasta",type:"main",diet:["balanced","high-protein"],kcal:720,ingredients:{"Pasta":"100 g","Tinned tuna":"1 can","Tomato passata":"200 g","Onions":"0.5","Olive oil":"1 tbsp"}},
 {id:"vegPasta",name:"Creamy vegetable pasta",type:"main",diet:["vegetarian"],kcal:680,ingredients:{"Pasta":"100 g","Frozen mixed vegetables":"220 g","Cooking cream":"80 ml","Garlic":"1 clove"}},
 {id:"salmon",name:"Oven salmon with potatoes",type:"main",diet:["balanced","high-protein"],kcal:740,ingredients:{"Salmon fillet":"180 g","Potatoes":"300 g","Green beans":"150 g","Olive oil":"1 tbsp"}},
 {id:"chickpea",name:"Chickpea vegetable curry",type:"main",diet:["balanced","vegetarian"],kcal:650,ingredients:{"Chickpeas":"1 can","Basmati rice":"80 g","Coconut milk":"120 ml","Frozen mixed vegetables":"180 g","Curry powder":"1 tbsp"}},
 {id:"wrap",name:"Chicken salad wraps",type:"main",diet:["balanced","high-protein"],kcal:620,ingredients:{"Chicken breast":"150 g","Tortilla wraps":"2","Lettuce":"80 g","Tomatoes":"1","Greek yogurt":"0.5 tub"}},
 {id:"vegWrap",name:"Hummus vegetable wraps",type:"main",diet:["vegetarian"],kcal:590,ingredients:{"Tortilla wraps":"2","Hummus":"80 g","Lettuce":"80 g","Tomatoes":"1","Carrots":"1"}},
 {id:"snack",name:"Fruit and yogurt",type:"snack",diet:["balanced","vegetarian","high-protein"],kcal:220,ingredients:{"Greek yogurt":"1 tub","Seasonal fruit":"1"}}
];
const BASE_PANTRY=["Olive oil","Salt","Black pepper","Paprika","Curry powder","Garlic","Onions"];
let products=[], state=loadState();
function loadState(){return JSON.parse(localStorage.getItem("pamplonaPantry")||"null")||{people:2,target:2100,budget:90,diet:"balanced",pantry:[...BASE_PANTRY],checkedPantry:[],bought:[],plan:[]}}
function save(){localStorage.setItem("pamplonaPantry",JSON.stringify(state))}
const el=id=>document.getElementById(id);
async function init(){products=await fetch("data/products.json").then(r=>r.json()).catch(()=>[]);bind();hydrateControls();generatePlan(false);renderProducts();}
function bind(){el("generateBtn").onclick=()=>generatePlan(true);el("printBtn").onclick=()=>window.print();el("resetBtn").onclick=()=>{localStorage.removeItem("pamplonaPantry");location.reload()};el("addPantryBtn").onclick=addPantry;el("customPantryInput").addEventListener("keydown",e=>{if(e.key==="Enter")addPantry()});el("productSearch").oninput=renderProducts;el("storeFilter").onchange=renderProducts;}
function hydrateControls(){el("peopleInput").value=state.people;el("calorieTargetInput").value=state.target;el("budgetInput").value=state.budget;el("dietInput").value=state.diet;[...new Set(products.map(p=>p.store))].sort().forEach(s=>el("storeFilter").insertAdjacentHTML("beforeend",`<option>${s}</option>`));}
function generatePlan(read=true){if(read){state.people=+el("peopleInput").value;state.target=+el("calorieTargetInput").value;state.budget=+el("budgetInput").value;state.diet=el("dietInput").value;}
 const mains=RECIPES.filter(r=>r.type==="main"&&r.diet.includes(state.diet));const breakfasts=RECIPES.filter(r=>r.type==="breakfast"&&r.diet.includes(state.diet));
 state.plan=DAYS.map((day,i)=>({day,breakfast:breakfast[i%breakfast.length],lunch:mains[i%mains.length],dinner:mains[(i+3)%mains.length],snack:RECIPES.find(r=>r.id==="snack")}));save();renderAll();}
function renderAll(){renderPlan();renderPantry();renderShopping();}
function renderPlan(){let weekly=0;el("mealPlan").innerHTML=state.plan.map(d=>{const total=d.breakfast.kcal+d.lunch.kcal+d.dinner.kcal+d.snack.kcal;weekly+=total;return `<article class="day-card"><h3>${d.day}</h3>${mealHTML("Breakfast",d.breakfast)}${mealHTML("Lunch",d.lunch)}${mealHTML("Dinner",d.dinner)}${mealHTML("Snack",d.snack)}<div class="daily-total">${total.toLocaleString()} kcal / person</div></article>`}).join("");const avg=Math.round(weekly/7);el("weekSummary").textContent=`Average ${avg.toLocaleString()} kcal per person/day · target ${state.target.toLocaleString()} kcal`;}
function mealHTML(label,r){return `<div class="meal"><small>${label}</small><strong>${r.name}</strong><span class="kcal">${r.kcal} kcal</span></div>`}
function ingredientNames(){return [...new Set(state.plan.flatMap(d=>[d.breakfast,d.lunch,d.dinner,d.snack]).flatMap(r=>Object.keys(r.ingredients)))].sort()}
function renderPantry(){const all=[...new Set([...state.pantry,...ingredientNames()])].sort();el("pantryList").innerHTML=all.map(item=>`<label class="check-row"><input type="checkbox" ${state.checkedPantry.includes(item)?"checked":""} onchange="togglePantry('${esc(item)}')"><span>${item}</span></label>`).join("")}
window.togglePantry=item=>{item=unesc(item);state.checkedPantry=state.checkedPantry.includes(item)?state.checkedPantry.filter(x=>x!==item):[...state.checkedPantry,item];save();renderShopping();}
function addPantry(){const v=el("customPantryInput").value.trim();if(!v)return;if(!state.pantry.includes(v))state.pantry.push(v);state.checkedPantry=[...new Set([...state.checkedPantry,v])];el("customPantryInput").value="";save();renderAll();}
function shoppingData(){const map={};state.plan.forEach(d=>[d.breakfast,d.lunch,d.dinner,d.snack].forEach(r=>Object.entries(r.ingredients).forEach(([name,qty])=>{map[name]??={name,uses:0,examples:new Set()};map[name].uses++;map[name].examples.add(qty)})));return Object.values(map).filter(x=>!state.checkedPantry.includes(x.name)).sort((a,b)=>a.name.localeCompare(b.name));}
function estimatePrice(name){const matches=products.filter(p=>p.name.toLowerCase().includes(name.toLowerCase())||name.toLowerCase().includes(p.name.split(" ")[0].toLowerCase()));return matches.length?Math.min(...matches.map(p=>p.price)):1.5;}
function renderShopping(){const data=shoppingData();let total=0;el("shoppingList").innerHTML=data.map(x=>{const price=estimatePrice(x.name);total+=price;const done=state.bought.includes(x.name);return `<div class="shopping-row ${done?"done":""}"><div class="shopping-main"><input type="checkbox" ${done?"checked":""} onchange="toggleBought('${esc(x.name)}')"><div><strong>${x.name}</strong><div class="muted">Used ${x.uses} times · ${[...x.examples].slice(0,2).join(" / ")}</div></div></div><span class="price">~€${price.toFixed(2)}</span></div>`}).join("")||`<p class="muted">Everything required is already marked as available.</p>`;el("estimatedTotal").textContent=`~€${total.toFixed(2)}`;el("estimatedTotal").title=total>state.budget?"Estimated total is above budget":"Estimated total is within budget";}
window.toggleBought=item=>{item=unesc(item);state.bought=state.bought.includes(item)?state.bought.filter(x=>x!==item):[...state.bought,item];save();renderShopping();}
function renderProducts(){const q=el("productSearch").value.toLowerCase();const store=el("storeFilter").value;let list=products.filter(p=>(store==="all"||p.store===store)&&(`${p.name} ${p.category}`.toLowerCase().includes(q)));const groups={};list.forEach(p=>(groups[p.name]??=[]).push(p));el("productResults").innerHTML=Object.values(groups).flatMap(group=>{const min=Math.min(...group.map(x=>x.price));return group.sort((a,b)=>a.price-b.price).map(p=>`<article class="product-card ${p.price===min&&group.length>1?"best":""}"><h3>${p.name}</h3><div class="product-meta"><span>${p.store} · ${p.unit}</span><strong>€${p.price.toFixed(2)}</strong></div></article>`)}).join("")||`<p class="muted">No matching products.</p>`;}
function esc(s){return s.replaceAll("'","&#39;")}function unesc(s){return s.replaceAll("&#39;","'")}
init();
